include:
  - project: "basworld/templates/pipelines"
    ref: "v1.3.1"
    file: "backend/api/template.yml"
  - project: "basworld/templates/pipelines"
    ref: "v1.3.1"
    file: "backend/jobs/feature-tests.yml"
  - project: "basworld/templates/pipelines"
    ref: "v1.3.1"
    file: "backend/jobs/mutation-tests.yml"

variables:
  ENABLE_AUTO_REVIEW: "true"
  ALLOW_FAILURE_STATIC_ANALYSIS: "true"
  SERVICE_NAME: "boilerplate-api"
  ECR_REPOSITORY: "976562007428.dkr.ecr.eu-central-1.amazonaws.com"
  CI_PIPELINE_IMAGE: "gitlab.bastrucks.com:5050/basworld/boilerplates/api/ci:1.0.0"