version: "3.8"
services:
    boilerplate-service:
        build:
            dockerfile: Dockerfile
        container_name: boilerplate-api
        ports:
            - ${NGINX_PORT:-8088}:80
            - ${NGINX_SSL_PORT:-8089}:443
        volumes:
            - .:/var/www/html
        networks:
            shared_network:
                aliases:
                    - boilerplate-api.bas.localhost
            boilerplate_api_network:
        restart: "no"
        labels:
            - "traefik.http.routers.http-boilerplate-api.rule=Host(`boilerplate-api.bas.localhost`)"
            - "traefik.http.routers.boilerplate-api.entrypoints=websecure"
            - "traefik.http.routers.boilerplate-api.rule=Host(`boilerplate-api.bas.localhost`)"
            - "traefik.http.routers.boilerplate-api.tls=true"
    mysqldb-server:
        build:
            dockerfile: ./docker/webserver/mysql.Dockerfile
        container_name: boilerplate-database
        networks:
            - default
            - shared_network
        ports:
            - ${DATABASE_SERVER_PORT:-3307}:3306
        restart: unless-stopped
networks:
    shared_network:
        external: true
        name: bas_shared_network
    boilerplate_api_network:
        driver: bridge
