global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          job: 'nginx'
          service: 'nginx'

  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php-fpm-exporter:9253']
        labels:
          job: 'php-fpm'
          service: 'php-fpm'

  - job_name: 'laravel'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['boilerplate-api:8080']
        labels:
          job: 'laravel'
          service: 'laravel-app'
